export const PROPERTY_TYPES = [
  { label: 'Satılık', value: 'SALE' },
  { label: 'Kiralık', value: 'RENT' },
] as const;

export const PROPERTY_STATUSES = [
  { label: 'Müsait', value: 'AVAILABLE', color: 'green' },
  { label: 'Opsiyonlu / Beklemede', value: 'PENDING', color: 'amber' },
  { label: 'Satıldı', value: 'SOLD', color: 'red' },
  { label: 'Kiralandı', value: 'RENTED', color: 'blue' },
] as const;

export const INQUIRY_STATUSES = [
  { label: 'Yeni / Beklemede', value: 'PENDING', color: 'amber' },
  { label: 'İletişime Geçildi', value: 'CONTACTED', color: 'blue' },
  { label: 'Tamamlandı / Kapandı', value: 'CLOSED', color: 'green' },
] as const;

export const CURRENCIES = [
  { label: '₺ - TRY', value: 'TRY', symbol: '₺' },
  { label: '$ - USD', value: 'USD', symbol: '$' },
  { label: '€ - EUR', value: 'EUR', symbol: '€' },
  { label: '£ - GBP', value: 'GBP', symbol: '£' },
] as const;

export const SORT_OPTIONS = [
  { label: 'En Yeni İlanlar', value: 'createdAt-desc' },
  { label: 'En Eski İlanlar', value: 'createdAt-asc' },
  { label: 'Fiyat: Düşükten Yükseğe', value: 'price-asc' },
  { label: 'Fiyat: Yüksekten Düşüğe', value: 'price-desc' },
  { label: 'Metrekare: Küçükten Büyüğe', value: 'area-asc' },
  { label: 'Metrekare: Büyükten Küçüğe', value: 'area-desc' },
] as const;

export const ROOM_OPTIONS = [
  { label: 'Stüdyo (1+0)', value: '0' },
  { label: '1+1', value: '1' },
  { label: '2+1', value: '2' },
  { label: '3+1', value: '3' },
  { label: '4+1', value: '4' },
  { label: '5+ ve üzeri', value: '5' },
] as const;

export const POPULAR_FEATURES = [
  'Asansör',
  'Otopark (Açık)',
  'Otopark (Kapalı)',
  'Balkon',
  'Teras',
  'Yüzme Havuzu',
  'Güvenlik / 7/24 Kamera',
  'Deniz Manzaralı',
  'Doğa / Şehir Manzaralı',
  'Ebeveyn Banyosu',
  'Giyinme Odası',
  'Akıllı Ev Sistemi',
  'Yerden Isıtma',
  'Doğalgaz / Kombi',
  'Klima',
  'Eşyalı',
  'Site İçerisinde',
  'Çocuk Oyun Parkı',
  'Fitness / Spor Salonu',
  'Sauna / Hamam',
  'Jeneratör',
  'Su Deposu',
  'Isı Yalıtımı',
  'Ses Yalıtımı',
  'Deprem Yönetmeliğine Uygun',
] as const;

export const CITIES_AND_DISTRICTS: Record<string, string[]> = {
  'İstanbul': [
    'Adalar',
    'Arnavutköy',
    'Ataşehir',
    'Avcılar',
    'Bağcılar',
    'Bahçelievler',
    'Bakırköy',
    'Başakşehir',
    'Bayrampaşa',
    'Beşiktaş',
    'Beykoz',
    'Beylikdüzü',
    'Beyoğlu',
    'Büyükçekmece',
    'Çatalca',
    'Çekmeköy',
    'Esenler',
    'Esenyurt',
    'Eyüpsultan',
    'Fatih',
    'Gaziosmanpaşa',
    'Güngören',
    'Kadıköy',
    'Kağıthane',
    'Kartal',
    'Küçükçekmece',
    'Maltepe',
    'Pendik',
    'Sancaktepe',
    'Sarıyer',
    'Silivri',
    'Sultanbeyli',
    'Sultangazi',
    'Şile',
    'Şişli',
    'Tuzla',
    'Ümraniye',
    'Üsküdar',
    'Zeytinburnu',
  ],
  'Ankara': [
    'Altındağ',
    'Çankaya',
    'Etimesgut',
    'Gölbaşı',
    'Keçiören',
    'Mamak',
    'Pursaklar',
    'Sincan',
    'Yenimahalle',
  ],
  'İzmir': [
    'Aliağa',
    'Balçova',
    'Bayraklı',
    'Bornova',
    'Buca',
    'Çeşme',
    'Çiğli',
    'Gaziemir',
    'Güzelbahçe',
    'Karabağlar',
    'Karşıyaka',
    'Konak',
    'Menderes',
    'Menemen',
    'Narlıdere',
    'Seferihisar',
    'Torbalı',
    'Urla',
  ],
  'Antalya': [
    'Aksu',
    'Alanya',
    'Döşemealtı',
    'Kaş',
    'Kemer',
    'Kepez',
    'Konyaaltı',
    'Kumluca',
    'Manavgat',
    'Muratpaşa',
    'Serik',
  ],
  'Muğla': [
    'Bodrum',
    'Dalaman',
    'Datça',
    'Fethiye',
    'Kavaklıdere',
    'Köyceğiz',
    'Marmaris',
    'Menteşe',
    'Milas',
    'Ortaca',
    'Ula',
    'Yatağan',
  ],
  'Bursa': [
    'Gemlik',
    'Gürsu',
    'İnegöl',
    'İznik',
    'Karacabey',
    'Kestel',
    'Mudanya',
    'Mustafakemalpaşa',
    'Nilüfer',
    'Osmangazi',
    'Yıldırım',
  ],
  'Yalova': ['Altınova', 'Armutlu', 'Çınarcık', 'Çiftlikköy', 'Merkez', 'Termal'],
  'Kocaeli': ['Başiskele', 'Çayırova', 'Darıca', 'Derince', 'Dilovası', 'Gebze', 'Gölcük', 'İzmit', 'Kandıra', 'Karamürsel', 'Kartepe', 'Körfez'],
  'Sakarya': ['Adapazarı', 'Akyazı', 'Arifiye', 'Erenler', 'Hendek', 'Karasu', 'Sapanca', 'Serdivan'],
  'Aydın': ['Didim', 'Efeler', 'Kuşadası', 'Nazilli', 'Söke'],
};

export const TURKISH_CITIES = Object.keys(CITIES_AND_DISTRICTS);

export const DEFAULT_PAGE_SIZE = 12;
export const ADMIN_PAGE_SIZE = 10;

export const NAV_LINKS = [
  { label: 'Ana Sayfa', href: '/' },
  { label: 'Tüm İlanlar', href: '/properties' },
  { label: 'Satılık', href: '/properties?type=SALE' },
  { label: 'Kiralık', href: '/properties?type=RENT' },
  { label: 'Hakkımızda', href: '/about' },
  { label: 'İletişim', href: '/contact' },
] as const;

export const ADMIN_NAV_LINKS = [
  { label: 'Kontrol Paneli', href: '/admin', icon: 'LayoutDashboard' },
  { label: 'İlan Yönetimi', href: '/admin/properties', icon: 'Building2' },
  { label: 'Kategoriler', href: '/admin/categories', icon: 'FolderTree' },
  { label: 'Gelen Talepler', href: '/admin/inquiries', icon: 'Mail' },
  { label: 'Site Ayarları', href: '/admin/settings', icon: 'Settings' },
] as const;
